name: OT238 CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Print Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
    - name: Build Project
      run: ./gradlew assemble
    - name: Run Lint
      run: ./gradlew lint
    - uses: EndBug/add-and-commit@v9
      with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Add Lint report'
          add: '/home/runner/work/OT238-client/OT238-client/app/build/reports/lint-results-debug.html --force'
          cwd: '.'    
