name: OT238 - Branch test

on:
  push:
    branches:
     -'features/**'
     -'feature/**'
     -'!main'
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Firebase JSON
      run: cat /home/runner/work/OT238-client/OT238-client/app/google-services.json | base64
    - name: Fetch Firebase Data
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/OT238-client/OT238-client/app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Unit Tests
      run: ./gradlew test
    - name: Print Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
    - name: Build Project
      run: ./gradlew assemble
